platform :ios, '15.0'

target 'iosApp' do
  use_frameworks!

  # Shared KMP framework
  pod 'composeApp', :path => '../composeApp'
  pod 'shared', :path => '../shared'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
