platform :ios, '15.0'

target 'iosApp' do
  use_frameworks!

  # Shared KMP framework
  pod 'composeApp', :path => '../composeApp'
  pod 'shared', :path => '../shared'

  # On-device LLM inference via llama.cpp
  pod 'llama', :git => 'https://github.com/ggml-org/llama.cpp.git', :tag => 'b5040'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
