name: iosApp
options:
  bundleIdPrefix: com.finuts
  deploymentTarget:
    iOS: "15.0"
  generateEmptyDirectories: true
  defaultConfig: Debug

packages:
  LLM:
    url: https://github.com/eastriverlee/LLM.swift.git
    from: "1.0.0"

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: ""
    CODE_SIGNING_REQUIRED: "NO"
    CODE_SIGNING_ALLOWED: "NO"

targets:
  iosApp:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: "15.0"
    sources:
      - path: iosApp
        type: group
    info:
      path: iosApp/Info.plist
      properties:
        CFBundleDisplayName: Finuts
        CFBundleName: $(PRODUCT_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        UILaunchScreen: {}
        CADisableMinimumFrameDurationOnPhone: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        INFOPLIST_FILE: iosApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.finuts.app
        SWIFT_VERSION: "5.0"
        OTHER_LDFLAGS: $(inherited) -framework composeApp
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: "NO"
      configs:
        Debug:
          SDKROOT: iphonesimulator
          FRAMEWORK_SEARCH_PATHS:
            - $(inherited)
            - $(SRCROOT)/../composeApp/build/bin/iosSimulatorArm64/debugFramework
        Release:
          SDKROOT: iphoneos
          FRAMEWORK_SEARCH_PATHS:
            - $(inherited)
            - $(SRCROOT)/../composeApp/build/bin/iosArm64/releaseFramework
    preBuildScripts:
      - name: Copy Compose Resources
        script: |
          # Copy Compose Multiplatform resources to app bundle
          RESOURCES_SRC="${SRCROOT}/../composeApp/build/generated/compose/resourceGenerator/preparedResources/commonMain/composeResources"
          RESOURCES_DST="${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/compose-resources/composeResources/finuts.composeapp.generated.resources"

          if [ -d "$RESOURCES_SRC" ]; then
            echo "Copying Compose resources from $RESOURCES_SRC to $RESOURCES_DST"
            mkdir -p "$RESOURCES_DST"
            cp -R "$RESOURCES_SRC"/* "$RESOURCES_DST/"
            echo "Compose resources copied successfully"
          else
            echo "Warning: Compose resources not found at $RESOURCES_SRC"
          fi
        basedOnDependencyAnalysis: false
    dependencies:
      - framework: ../composeApp/build/bin/iosSimulatorArm64/debugFramework/composeApp.framework
        embed: true
      - package: LLM

schemes:
  iosApp:
    build:
      targets:
        iosApp: all
    run:
      config: Debug
    archive:
      config: Release
