package com.finuts.ai.model

import com.finuts.domain.entity.CategorizationResult
import com.finuts.domain.entity.import.ImportedTransaction
import kotlinx.datetime.DatePeriod
import kotlinx.datetime.LocalDate
import kotlinx.datetime.TimeZone
import kotlinx.datetime.minus
import kotlinx.datetime.toLocalDateTime
import kotlinx.serialization.Serializable

/**
 * Result wrapper for all AI operations.
 */
sealed class AIResult<out T> {
    data class Success<T>(val data: T, val tokensUsed: Int = 0) : AIResult<T>()
    data class Error(val message: String, val cause: Throwable? = null) : AIResult<Nothing>()
    data object CostLimitExceeded : AIResult<Nothing>()
    data object ProviderUnavailable : AIResult<Nothing>()
}

/**
 * Document parsing result from AI.
 */
data class DocumentParseResult(
    val transactions: List<ImportedTransaction>,
    val documentType: String,
    val confidence: Float,
    val tokensUsed: Int
)

/**
 * Spending insights generated by AI.
 */
@Serializable
data class SpendingInsights(
    val period: Period,
    val totalSpent: Long,
    val topCategories: List<CategorySpending>,
    val comparisonToPrevious: Float, // percentage change
    val insights: List<InsightItem>,
    val recommendations: List<String>
)

@Serializable
data class CategorySpending(
    val categoryId: String,
    val categoryName: String,
    val amount: Long,
    val percentage: Float,
    val trend: Trend
)

@Serializable
enum class Trend { UP, DOWN, STABLE }

@Serializable
data class InsightItem(
    val type: InsightType,
    val title: String,
    val description: String,
    val severity: Severity = Severity.INFO
)

@Serializable
enum class InsightType {
    SPENDING_SPIKE,
    UNUSUAL_TRANSACTION,
    RECURRING_DETECTED,
    BUDGET_WARNING,
    SAVINGS_OPPORTUNITY,
    GOAL_PROGRESS
}

@Serializable
enum class Severity { INFO, WARNING, ALERT }

/**
 * Time period for analytics.
 */
@Serializable
data class Period(
    val start: LocalDate,
    val end: LocalDate
) {
    companion object {
        fun lastDays(days: Int): Period {
            val now = kotlinx.datetime.Instant.fromEpochMilliseconds(
                kotlin.time.Clock.System.now().toEpochMilliseconds()
            )
            val end = now.toLocalDateTime(TimeZone.currentSystemDefault()).date
            val start = end.minus(DatePeriod(days = days))
            return Period(start, end)
        }
    }
}

/**
 * Anomaly detected by AI.
 */
@Serializable
data class Anomaly(
    val transactionId: String,
    val type: AnomalyType,
    val description: String,
    val severity: Severity
)

@Serializable
enum class AnomalyType {
    UNUSUAL_AMOUNT,
    UNUSUAL_CATEGORY,
    UNUSUAL_TIME,
    DUPLICATE_SUSPECTED,
    FRAUD_SUSPECTED
}

/**
 * Chat response from AI advisor.
 */
data class ChatResponse(
    val message: String,
    val suggestions: List<String> = emptyList(),
    val actions: List<QuickAction> = emptyList(),
    val sources: List<String> = emptyList()
)

@Serializable
data class QuickAction(
    val type: ActionType,
    val label: String,
    val payload: Map<String, String> = emptyMap()
)

@Serializable
enum class ActionType {
    CREATE_BUDGET,
    VIEW_CATEGORY,
    SET_GOAL,
    EXPORT_REPORT,
    SHOW_TRANSACTIONS
}

/**
 * Prediction result.
 */
@Serializable
data class Predictions(
    val type: PredictionType,
    val predictions: List<PredictionItem>
)

@Serializable
enum class PredictionType {
    MONTHLY_SPENDING,
    CATEGORY_SPENDING,
    RECURRING_PAYMENTS
}

@Serializable
data class PredictionItem(
    val label: String,
    val predictedAmount: Long,
    val confidence: Float
)

/**
 * Budget suggestion from AI.
 */
@Serializable
data class BudgetSuggestion(
    val categoryId: String,
    val suggestedAmount: Long,
    val reasoning: String,
    val confidence: Float
)

/**
 * Recurring pattern detected.
 */
@Serializable
data class RecurringPattern(
    val merchantName: String,
    val averageAmount: Long,
    val frequency: String, // "monthly", "weekly", etc.
    val nextExpectedDate: LocalDate?,
    val confidence: Float
)
